# Generated by Django 4.0 on 2022-01-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_comment_post_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
