# Generated by Django 4.0 on 2022-01-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
