# Generated by Django 4.0 on 2022-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='desc',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
    ]
