# Generated by Django 4.0 on 2022-02-10 19:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Post', '0011_alter_avatar_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='link',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField()),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
