# Generated by Django 4.0 on 2022-02-10 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_remove_avatar_desc_remove_avatar_link_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='desc',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
