# Generated by Django 4.0 on 2022-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_avatar_desc_avatar_link_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='desc',
            field=models.TextField(),
        ),
    ]
