# Generated by Django 4.0 on 2022-02-10 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_alter_avatar_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
